"""Added weekly money

Revision ID: 018d229f73ea
Revises: 33614a7651ec
Create Date: 2023-07-28 09:49:01.290155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018d229f73ea'
down_revision = '33614a7651ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_money', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weekly_money')

    # ### end Alembic commands ###
